#!/bin/sh
# /etc/init.d/vncboot
# Customised by Stewart Watkiss
#http://www.penguintutor.com/linux/tightvnc
# Set the VNCUSER variable to the name of the user to start tightvncserver under
#Modified by Vasilis Nicolaou to contain status
### BEGIN INIT INFO
# Provides:          vncboot
# Required-Start:    $network $local_fs 
# Required-Stop:     
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# X-Interactive: true
# Short-Description: Starts the tightvncserver on display 1
# Description:       Starts the tightvncserver on display 1 port 5901 
### END INIT INFO
VNCUSER=$(whoami)
eval cd ~$VNCUSER
case "$1" in
 start)
   if [ -n "$(pgrep Xtightvnc)" ]; then
    echo "Service is already running"
    exit 0
   fi
   su $VNCUSER -c '/usr/bin/vncserver :1 -geometry 1280x800 -depth 16'
   echo "Starting TightVNC server for $VNCUSER "
   ;;
 stop)
   if [ -z "$(pgrep Xtightvnc)" ]; then
    echo "Service is not running"
    exit 0
   fi 
   pkill Xtightvnc || exit 1
   echo "Tightvncserver stopped"
   ;;
 restart)
  $0 stop
  $0 start
   ;;
 status)
    if [ -n "$(pgrep Xtightvnc)" ]; then
        echo "Service is running with id $(pgrep Xtightvnc)"
        exit 0
    else
        echo "Service is down"
        exit 3
    fi 
    ;;
 *)
   echo "Usage: /etc/init.d/tightvncserver {start|stop|status}"
   exit 1
   ;;
esac
exit 0
