#!/bin/bash
update_output=`pi-update -d`
need_for_update=`echo "$update_output" | grep "updates found"`

if [ "X$need_for_update" != "X" ] && [ ! -z "$need_for_update" ]; then
    pi-update -a;
fi

exit 0;

