#!/bin/sh
sudo apt-get update && apt-get -s -o Debug::NoLocking=true upgrade | grep ^Inst >/usr/lib/piwebagent2/update_check |\
 cut -f '2-4' -d ' ' | tr -d '[' | tr -d ']' | tr -d '(' 
chown piwebagent2 /usr/lib/piwebagent2/update_check