#!/bin/bash
buffers=`cat '/proc/meminfo' | grep "Buffers:" | \
    head -n 1 | cut -d ':' -f 2 | \
    cut -d 'k' -f 1 | tr -d ' '`
cached=`cat '/proc/meminfo' | grep "Cached:" | \
    head -n 1 | cut -d ':' -f 2 | \
    cut -d 'k' -f 1 | tr -d ' '`     
function getSizeInMB {
    num=`cat '/proc/meminfo' | grep "$1" | \
    head -n 1 | cut -d ':' -f 2 | \
    cut -d 'k' -f 1 | tr -d ' '`
    
    if [ "$1" = "MemFree" ]; then
        num=$(($num+$buffers+$cached))
    fi
    result=$(($num/1024))
    echo "$result MB"
}
function getSize {
    num=`cat '/proc/meminfo' | grep "$1" | \
    head -n 1 | cut -d ':' -f 2 | \
    cut -d 'k' -f 1 | tr -d ' '`
    if [ "$1" = "MemFree" ]; then
        num=$(($num+$buffers+$cached))
    fi
    result=$(($num/1024))
    echo "$result"
}
if [ -z "$1" ]; then
    memtotal=$(getSizeInMB "MemTotal")
    memfree=$(getSizeInMB "MemFree")
    swapTotal=$(getSizeInMB "SwapTotal")
    swapFree=$(getSizeInMB "SwapFree")

    echo "Memory: $memtotal Total / $memfree Free<br>"
    echo "Swap: $swapTotal Total / $swapFree Free"
    exit 0
fi

echo $(getSize "$1")

        
